// let Worker1  = {
//     fullName : "AyanKhurram",
//     Age : 15,
//     serviceRating : true,
//     Ratting : 4,
//     Skill : "WebDeveloper",
// };
// console.log (Worker1)
// let Worker2  = {
//     fullName : "Shariq",
//     Age : 25,
//     serviceRating : true,
//     Ratting : 4.5,
//     Skill : "WebDeveloper",
// };
// console.log (Worker2)
// let Worker3  = {
//     fullName : "Ahsan",
//     Age : 18,
//     serviceRating : true,
//     Ratting : 3.5,
//     Skill : "WebDeveloper",
// };
// console.log (Worker3)//
// let a = 5;
// let b = 2;

// console.log ("a = ", a, " & b = ", b );
// console.log ("a + b = " , a + b);
// console.log ("a - b = " , a - b);
// console.log ("a * b = " , a * b);
// console.log ("a / b = " , a / b);
// console.log ("a % b = " , a % b);
// console.log ("a ** b = " , a ** b);
// let a = 5;
// let b = 2;

// console.log ("a = ", a, " & b = ", b );
// console.log ("a++ = ", a++);
// console.log ("a = ", a)
// let a = 5;
// let b = 2;

// a **= 4;
// console.log ("a = ", a)
// let a  6;
// let b = 5;

// console.log ("a >= b", a >= b);
// let a = 6;
// let b = 5;
// // console.log ("!(6 < 5) =" , !(a === 6));
// let num = 7;
// if (num%2 === 0) {
//     console.log("even");
// } else {
//     console.log ("odd")};

// if (age >= 18) {
//     console.log ("You can Vote")
// }
// if (age < 18) {
//     console.log ("You CANNOT Vote")
// let age = 16;
// let result = age >= 18 ? "adult" : "notAdut";
// console.log (result);
// let score = prompt( "Only say Score:::Number of your Score (0-100):");
// let grade;

// if (score >= 90 && score <= 100) {
//     grade = "A"
// }
// if (score >= 70 && score <= 89) {
//     grade = "B"
// }
// if (score >= 60 && score <= 69) {
//     grade = "C"
// }
// if (score >= 50 && score <= 49) {
//     grade = "D"
// }
// if (score >= 0 && score <= 49) {
//     grade = "F"
// }
// console.log("According your Score Your Grade" , grade);